(load 'minmax.lsp)
;this needs 
(defun make-move (position player ply)
	(let (x)
		(setf x (minimax position ply))
		(cadr x)
	)
)
(defun humanmove(validMoves player state)
	(let (coords)
		(cond ((equal validMoves nil) (format t "You have no moves currently"))
			(t 
				(format t "Enter a move: ") 
				(dotimes (x 2)
					(setf coords (append coords (list (read))))
				)
			)
		)
	)
)
